#' Extract Predictor Variable Importance from a Fusion Model
#'
#' @description
#' Extracts feature importance metrics for the underlying LightGBM models stored
#' within a microdata fusion model file (\code{.fsn}). Returns both per-model
#' detailed metrics and pooled summary metrics averaged across all target sub-models.
#'
#' @param fsn Character string. Path to a valid microdata fusion model file (\code{.fsn})
#'   previously generated by \code{\link{train}}.
#'
#' @details
#' Microdata fusion models trained via \code{\link{train}} consist of an archive of
#' LightGBM models corresponding to different target variables (\eqn{y}) and estimation
#' types—such as mean (\code{"m"}), zero-indicator (\code{"z"}), or conditional
#' quantiles (\code{"q"}).
#'
#' \code{importance()} uncompresses the \code{.fsn} archive into a temporary session
#' directory, parses each LightGBM text model using \code{\link[lightgbm]{lgb.load}},
#' and calculates feature importance via \code{\link[lightgbm]{lgb.importance}}.
#'
#' Three standard LightGBM importance metrics are computed:
#' \describe{
#'   \item{\code{gain}}{The relative contribution of a predictor variable to the model,
#'     measured by the total gain of splits using that feature. \strong{Gain is the primary
#'     and recommended metric for evaluating predictor importance.}}
#'   \item{\code{cover}}{The relative number of observations (samples) impacted by splits
#'     containing the feature.}
#'   \item{\code{frequency}}{The relative number of times a feature is used across all split
#'     trees in the model.}
#' }
#'
#' In the \code{$summary} output, importance metrics are averaged across all underlying sub-models
#' for a given target variable (\eqn{y}) and normalized so that feature contributions sum to 1.0
#' per target variable. Factor levels for predictor variables (\code{x}) in \code{$summary} are
#' pre-ordered by overall mean gain to facilitate clear, ordered visualizations (e.g., via \code{ggplot2}).
#'
#' @return A named \code{list} containing two data frames:
#' \describe{
#'   \item{\code{summary}}{A \code{data.frame} providing pooled, normalized importance
#'     metrics (\code{gain}, \code{cover}, \code{frequency}) averaged across sub-models for each
#'     target variable (\code{y}). Predictor names (\code{x}) are pre-formatted as ordered factors
#'     for straightforward plotting.}
#'   \item{\code{detailed}}{A \code{data.frame} providing raw, un-normalized importance
#'     metrics for every individual LightGBM sub-model (\code{model}) across all target
#'     variables (\code{y}).}
#' }
#'
#' @examples
#' \dontrun{
#' library(fusionModel)
#' library(ggplot2)
#'
#' # Build a fusion model using RECS sample microdata
#' # Note: train() writes "fusion_model.fsn" to the working directory
#' fusion.vars <- c("electricity", "natural_gas", "aircon")
#' predictor.vars <- names(recs)[2:12]
#' fsn.path <- train(data = recs, y = fusion.vars, x = predictor.vars)
#'
#' # Extract predictor variable importance
#' ximp <- importance(fsn.path)
#'
#' # Inspect overall summary results
#' head(ximp$summary)
#'
#' # Plot relative gain across target variables
#' ggplot(ximp$summary, aes(x = x, y = gain, fill = y)) +
#'   geom_col(show.legend = FALSE) +
#'   facet_wrap(~ y, scales = "free_y") +
#'   coord_flip() +
#'   labs(
#'     x = "Predictor Variable",
#'     y = "Normalized Relative Gain",
#'     title = "Predictor Importance by Target Variable"
#'   ) +
#'   theme_bw()
#'
#' # View raw, per-model detailed metrics
#' head(ximp$detailed)
#' }
#'
#' @export

importance <- function(fsn) {

  stopifnot(exprs = {
    file.exists(fsn) & endsWith(fsn, ".fsn")
  })

  # Create a session-isolated temporary directory to extract .fsn archive contents
  td <- tempfile()
  dir.create(td)

  # Map file and sub-directory structure inside the .fsn zip archive
  fsn.files <- zip::zip_list(fsn)
  pfixes <- sort(unique(dirname(fsn.files$filename)))
  pfixes <- pfixes[pfixes != "."]

  # Extract model sub-files to the temporary directory
  zip::unzip(zipfile = fsn, exdir = td)

  # Extract per-model variable importance metrics for each sub-folder/prefix
  detail <- lapply(1:length(pfixes), FUN = function(i) {
    mods <- grep(pattern = utils::glob2rx(paste0(pfixes[i], "*.txt")), x = fsn.files$filename, value = TRUE)
    mods %>%
      lapply(FUN = function(m) {
        y <- sub("_[^_]+$", "", basename(m))
        n <- sub(".txt", "", sub(paste0(y, "_"), "", basename(m), fixed = TRUE), fixed = TRUE)
        mod <- lightgbm::lgb.load(filename = file.path(td, m))
        imp <- lightgbm::lgb.importance(mod) %>%
          mutate(y = y,
                 model = n)
        return(imp)
      }) %>%
      data.table::rbindlist()
  }) %>%
    data.table::rbindlist() %>%
    rename_with(tolower) %>%
    rename(x = feature) %>%
    select(y, model, x, everything()) %>%
    as.data.frame()

  # Calculate pooled summary across sub-models per target variable (y)
  smry <- detail %>%
    group_by(y, x) %>%
    summarize(across(gain:frequency, mean), .groups = "drop_last") %>%
    mutate(across(gain:frequency, ~ .x / sum(.x))) %>%  # Scale metrics so contributions sum to 1 per y
    ungroup() %>%
    arrange(y, -gain)

  # Determine optimal plotting display order for predictors based on average gain
  yvars <- unique(detail$y)
  xord <- smry %>%
    filter(!x %in% yvars) %>%
    group_by(x) %>%
    summarize(across(gain, mean)) %>%
    arrange(gain) %>%
    pull(x)

  # Assign factor levels to ensure clean ordering in downstream visualizations
  smry$y <- factor(smry$y, levels = yvars)
  smry$x <- factor(smry$x, levels = c(rev(yvars), xord))

  out <- list(summary = smry, detailed = detail)
  return(out)

}
