#' Validate and Plot Microdata Fusion Results
#'
#' @description
#' `validate()` performs internal validation analyses on fused microdata to assess
#' how well synthetic (fused) variables reproduce the statistical relationships,
#' point estimates, and sampling uncertainties present in observed donor microdata
#' across various population subsets.
#'
#' `plot_valid()` generates conditional performance graphics and diagnostic plots
#' from the results returned by `validate()`, with options to display overall summary
#' curves or save plots directly to disk.
#'
#' @param observed Data frame or data.table. The observed donor data used to train the
#'   underlying fusion model. Must contain the subset variables and weighting column.
#' @param implicates Data frame or data.table. Implicates of synthetic (fused) variables
#'   generated by \code{\link{fuse}}. Implicates must be row-stacked and identified
#'   by an integer column \code{M}.
#' @param subset_vars Character vector. Names of columns in \code{observed} used to
#'   partition the dataset into evaluation subsets. Subsets are formed from main effects
#'   and two-way interactions. Continuous or ordered factor variables in \code{subset_vars}
#'   are automatically binned into 5-level ordered factors via 1D k-means clustering.
#' @param weight Character. Column name of sample weights in \code{observed}. If \code{NULL}
#'   (default), uniform unit weights are assumed.
#' @param min_size Integer. Minimum required sample size for a subset to be included
#'   in evaluation (default is 30). Subsets with fewer observations are excluded.
#' @param plot Logical. If \code{TRUE} (default), \code{\link{plot_valid}} is called
#'   automatically inside \code{validate()} to produce summary diagnostics.
#' @param cores Integer. Number of CPU cores for parallel execution (Unix/Linux systems).
#'   Default is 1.
#' @param valid An object of class \code{validate} returned by a call to \code{validate()}.
#' @param y Character vector. Optional subset of fusion variable names to process or plot.
#'   If \code{NULL} (default), all fusion variables present in \code{valid} are included.
#' @param path Character. Directory path where \code{.png} graphic files will be written.
#'   If \code{NULL} (default), graphics are returned in memory without writing to disk.
#' @param ... Additional arguments passed to \code{\link[ggplot2]{ggsave}} when saving
#'   plots to disk (e.g., \code{width}, \code{height}, \code{dpi}).
#'
#' @details
#' The primary goal of `validate()` is to verify the scientific utility and empirical accuracy
#' of synthetic variables generated through microdata fusion. Validation compares point
#' estimates (means and proportions) and confidence interval bounds between synthetic multiple
#' implicates and observed donor data across population subsets of varying granularities.
#'
#' For categorical variables, factor levels are one-hot encoded into binary indicators prior
#' to evaluation. Point estimates and Rubin's rules-based standard errors are calculated
#' for each subset using \code{\link{analyze}}-style operations.
#'
#' **Diagnostic Metrics in `plot_valid()`:**
#' \itemize{
#'   \item **Point Estimate Error (`est`):** Absolute percent error comparing simulated
#'     to observed point estimates.
#'   \item **Value Added (`vad`):** Performance relative to a naive baseline estimate
#'     (overall sample mean).
#'   \item **Relative Uncertainty (`moe`):** Ratio of simulated-to-observed margins of
#'     error (90\% confidence intervals).
#' }
#'
#' Conditional quantile smoothing (using quantile regression over subset proportions) is
#' applied to display trend lines illustrating expected accuracy across small to large subsets.
#'
#' @return
#' If \code{plot = FALSE}, `validate()` returns a data frame of class \code{validate}
#' containing row-level comparison metrics across evaluated subsets.
#'
#' If \code{plot = TRUE} (or when invoking `plot_valid()`), a list of class \code{validate}
#' is returned containing:
#' \itemize{
#'   \item \code{plots}: A nested list of \code{\link[ggplot2]{ggplot}} objects. Contains
#'     overall comparative plots (\code{est}, \code{vad}, \code{moe}) as well as
#'     variable-specific scatter/trend diagnostic panels.
#'   \item \code{perf}: A data frame summarizing mean smoothed error metrics across subset ranges.
#'   \item \code{smooth}: A data.table containing conditional quantile smoothing curve coordinates.
#'   \item \code{data}: A data frame of raw validation subset calculations.
#' }
#'
#' @examples
#' \dontrun{
#' # Build a fusion model using RECS microdata
#' fusion.vars <- c("electricity", "natural_gas", "aircon")
#' predictor.vars <- names(recs)[2:12]
#' fsn.path <- train(data = recs,
#'                   y = fusion.vars,
#'                   x = predictor.vars,
#'                   weight = "weight")
#'
#' # Fuse back onto donor data (generating 20 implicates)
#' sim <- fuse(data = recs,
#'             fsn = fsn.path,
#'             M = 20)
#'
#' # Perform validation across population subsets
#' valid <- validate(observed = recs,
#'                   implicates = sim,
#'                   subset_vars = c("income", "education", "race", "urban_rural"),
#'                   weight = "weight")
#'
#' # Inspect multi-variable summary diagnostics
#' valid$plots$est
#' valid$plots$moe
#'
#' # Inspect single-variable diagnostic panel
#' valid$plots$electricity$est
#'
#' # Re-run plot generation separately to save PNG images to disk
#' valid_saved <- plot_valid(valid,
#'                           path = file.path(getwd(), "validation_plots"),
#'                           width = 8, height = 6)
#' }
#'
#' @export

#-----

# library(fusionModel)
# library(dplyr)
# library(data.table)
# library(purrr)
# library(ggplot2)
# library(fst)
# source("R/utils.R")
# source("R/analyze_funs.R")
# observed <- read_fst("~/Documents/Projects/fusionData/fusion/RECS/2015/2015/input/RECS_2015_2015_train.fst")
# implicates <- read_fsd("~/Documents/Projects/fusionData/fusion/RECS/2015/2015/output/RECS_2015_2015_valid.fsd")
# subset_vars = c("moneypy__hincp", "hhage__agep", "householder_race__rac1p", "education__schl", "nhsldmem__np", "kownrent__ten", "loc..recs_division")
# weight = "weight"
# min_size = 30
# plot = TRUE
# cores = 1

#-----

validate <- function(observed,
                     implicates,
                     subset_vars,
                     weight = NULL,
                     min_size = 30,
                     plot = TRUE,
                     cores = 1) {

  t0 <- Sys.time()

  obs <- as.data.table(observed)
  sim <- as.data.table(implicates)
  rm(observed, implicates)

  # Check inputs
  stopifnot({
    all(setdiff(names(sim), "M") %in% names(obs))
    is.character(subset_vars) & all(subset_vars %in% names(obs))
    is.null(weight) | (length(weight) == 1 & weight %in% names(obs))
    min_size > 0
    is.logical(plot)
    cores > 0 & cores %% 1 == 0
  })

  # Check that input dimensions are consistent with one another
  N <- nrow(obs)
  Mimp <- max(sim$M)
  if (Mimp == 1) stop("Validation requires 'implicates' to contain more than one implicate")
  nM <- sim[, .N, by = M]
  stopifnot(N == nrow(sim) / Mimp)
  stopifnot(all(nM$M %in% seq_len(Mimp)))
  stopifnot(all(nM$N == N))

  if (is.null(weight)) {
    cli::cli_inform("Assuming uniform sample weights")
    obs$W <- 1L
  } else {
    setnames(obs, weight, "W")
    obs[, W := W / mean(W)]
  }

  # Variables for which estimates will be computed
  y <- setdiff(names(sim), "M")
  yN <- length(y)  # Reported to console later
  if (any(y %in% subset_vars)) stop("Fused variabes are not allowed as 'subset_vars'")

  # Generate list of combinations of subset variables to test
  # Restricted to no more than 2 subset variables per combination (m = 2)
  scomb <- as.list(subset_vars)
  if (length(subset_vars) > 1) scomb <- c(scomb, combn(subset_vars, m = 2, simplify = FALSE))

  # Restrict 'obs' to only the necessary variables
  v <- c("W", y, subset_vars)
  obs <- obs[, ..v]

  #---

  # Which subset_vars are numeric or ordered factor?
  sclus <- names(which(sapply(obs[, ..subset_vars], function(x) is.ordered(x) | is.numeric(x))))

  # Convert numeric and ordered factor subset variables into clustered, ordered factors with k levels via uniCluster()
  for (v in sclus) set(obs, j = v, value = uniCluster(x = obs[[v]], k = 5))

  #---

  # Convert logical 'y' variables to factor so they are handled appropriately
  ylog <- names(which(sapply(obs[, ..y], is.logical)))
  for (v in ylog) {
    set(obs, j = v, value = as.factor(obs[[v]]))
    set(sim, j = v, value = as.factor(sim[[v]]))
  }

  # One-hot encode the y factor variables
  yfct <- names(which(sapply(obs[, ..y], is.factor)))
  if (length(yfct) > 0) {
    cli::cli_inform("One-hot encoding categorical fusion variables")

    # 1. Encode ONLY the y factor columns
    obs_fct_encoded <- one_hot(obs[, ..yfct], dropOriginal = TRUE, dropUnusedLevels = FALSE)
    sim_fct_encoded <- one_hot(sim[, ..yfct], dropOriginal = TRUE, dropUnusedLevels = FALSE)

    # Extract the attribute before dropping/combining
    dlink <- attr(obs_fct_encoded, "one_hot_link")

    # 2. Get the new dummy column names
    encoded_names <- setdiff(names(obs_fct_encoded), yfct)

    # 3. Update 'y' vector to replace factor targets with dummy targets
    y <- c(setdiff(y, yfct), encoded_names)

    # 4. Remove original factor y-variables and append dummy columns
    # (subset_vars remain completely untouched)
    obs <- cbind(obs[, .SD, .SDcols = !yfct], obs_fct_encoded[, ..encoded_names])
    sim <- cbind(sim[, .SD, .SDcols = !yfct], sim_fct_encoded[, ..encoded_names])

    attr(obs, "one_hot_link") <- dlink
  }

  #---

  # Detect and impute any missing values in 'observed'
  # Note that 'simulated' should not have any NA's by design
  na.cols <- names(which(sapply(obs, anyNA)))
  if (length(na.cols) > 0) {
    cli::cli_inform("Missing values imputed for the following variable(s): {paste(na.cols, collapse = ', ')}")
    for (j in na.cols) {
      x <- observed[[j]]
      ind <- is.na(x)
      observed[ind, j] <- imputationValue(x, ind)
    }
  }

  #---

  # Combine observed and simulated data
  v <- c("W", subset_vars)
  sim <- cbind(sim, obs[rep(1:N, Mimp), ..v])

  # Key the data.tables for speed in 'by' operations below
  setkeyv(sim, c("M", subset_vars))
  setkeyv(obs, subset_vars)

  # Report the overall correlation between observed and simulated fusion variables
  # This is a quick check if the simulated data are simply replicating the original values (over-fitting)
  ycor <- sapply(y, function(v) suppressWarnings(cor(rep(obs[[v]], Mimp), sim[, ..v])))
  cli::cli_inform("Correlation between observed and fused values:")
  print(summary(ycor), digits = 2)

  # Function to compute margin of error (MOE)
  # p = 0.95 entails a 90% confidence interval
  calcMOE <- function(d, p = 0.95) {
    d %>%
      mutate(
        moe = se * qt(p, df)
      )
  }

  #---

  # Process a particular combination of subsetting variables

  processSubset <- function(iset) {

    svar <- scomb[[iset]]

    # Calculate the share of observations within each subset, using the observed data
    subshr <- obs[, .(share = .N / N), by = svar]
    subshr <- subshr[share >= min_size / N]
    subshr$id <- paste(iset, 1:nrow(subshr), sep = "_")

    # Restrict 'obs' and 'sim' to subsets with at least 'min_size' observations
    obs <- obs[subshr, on = svar]
    sim <- sim[subshr, on = svar]

    #---

    # Calculate outcomes for the observed data
    g <- obs[, lapply(.SD, weighted_mean, w1 = W, w2 = W), by = svar, .SDcols = y]
    g$metric <- rep(c("estimate1", "estimate2", "variance"), times = nrow(g) / 3)
    g <- melt(g, measure.vars = y, variable.name = "y")
    g <- dcast(g, ... ~ metric, value.var = "value")
    g <- g[subshr, on = svar]  # Adds "share" and "id" variables
    g <- mutate(g,
                est = estimate1,
                se = sqrt(variance),
                df = as.integer(share * N - 1)) %>%
      select(-estimate1, -estimate2, -variance) %>%
      calcMOE()

    #---

    # Calculate outcomes for the simulated data

    # Weighted mean and variance of the mean for each implicate
    d <- sim[, lapply(.SD, weighted_mean, w1 = W, w2 = W), by = c("M", svar), .SDcols = y]
    #d <- sim[, lapply(.SD, weighted_mean, w1 = W, w2 = W), by = c("M", svar), .SDcols = ysim]
    d$metric <- rep(c("estimate1", "estimate2", "variance"), times = nrow(d) / 3)
    d <- melt(d, id.vars = c("M", "metric", svar), variable.name = "y")
    d <- dcast(d, ... ~ metric, value.var = "value")

    # Calculate the necessary quantities
    # est: Point estimates
    # ubar: Mean of the within-implicate variances
    # b: Variance of estimates, across the implicates (approximated by variance of mixture of normal distributions)
    d <- d[, .(est = mean(estimate1),
               ubar = mean(variance),
               b = var(estimate1)),
           #b = (sum(estimate1 ^ 2 + variance) / Mimp) - mean(estimate1) ^ 2),  # Conservative approximation of var(estimate1); does not risk b1 < ubar
           by = c(svar, "y")]

    # Adds "share" and "id" variables
    d <- d[subshr, on = svar]

    # Calculate margin of error
    #maxr <- maxr_fun(Mimp)
    d <- mutate(d,
                # b = ifelse(ubar / b > maxr, ubar / maxr, b),
                # b = ifelse(ubar == 0, 0, b),

                # Rubin 1987
                se = sqrt(ubar + (1 + Mimp^(-1)) * b),
                r = (1 + Mimp^(-1)) * b / ubar,
                df = (Mimp - 1) * (1 + r^(-1)) ^ 2,
                df = ifelse(is.infinite(df), as.integer(share * N - 1), df), # Set 'df' to standard value if Inf is returned by Rubin's formula (i.e. when b = 0; no variance across implicates)
                r = NULL

                # Reiter and Raghunathan (2007)
                # se = sqrt(b * (1 + 1 / Mimp) - ubar),
                # df = (Mimp - 1) * (1 - Mimp * ubar / ((Mimp + 1) * b)) ^ 2,
                # df = ifelse(se == 0, 1, df)
    ) %>%
      select(-ubar, -b, -share, -id) %>%
      #select(-ubar, -b) %>%
      calcMOE()

    # Merge observed and simulated results
    comp <- merge(g, d, by = c(svar, "y"), suffixes = c(".obs", ".sim")) %>%
      select(-all_of(svar))
    return(comp)

  }

  #---

  # Process each subset combination in 'scomb'
  cli::cli_inform("Processing validation analyses for {yN} fusion variable{?s}")
  comp <- parallel::mclapply(seq_along(scomb), processSubset, mc.cores = cores) %>%
    rbindlist()

  #---

  # Add the observed mean estimates (est.mean)
  avg <- matrixStats::colWeightedMeans(x = as.matrix(obs[, ..y]), w = obs$W)
  set(comp, j = "est.mean", value = avg[match(comp$y, names(avg))])

  #---

  # Add original factor variable levels, if necessary
  if (length(yfct) > 0) {
    comp <- merge(x = comp, y = attr(obs, "one_hot_link"), by.x = "y", by.y = "dummy", all.x = TRUE, sort = FALSE)
    comp <- comp %>%
      mutate(y = ifelse(is.na(level), y, original)) %>%
      select(-original)
  } else {
    comp$level <- NA
  }

  #---

  # Report total unique subsets analyzed
  cli::cli_inform("Performed {nrow(comp)} analyses across {uniqueN(comp$id)} subsets")

  # Data frame with comparison results
  keep <- c("id", "share", "y", "level", "est.obs", "moe.obs", "est.sim", "moe.sim", "est.mean")
  result <- comp[, ..keep]
  result$y <- as.character(result$y)
  class(result) <- c("validate", class(comp))

  # Clean up
  rm(obs, sim, comp)

  #---

  # Check if ggplot2 is installed; if so, call plot_valid() prior to returning result
  if (plot) {
    suppressMessages(ok <- require(ggplot2, quietly = TRUE, warn.conflicts = FALSE))
    if (ok) {
      result <- plot_valid(result, cores = cores)
      class(result) <- c("validate", class(result))
    } else {
      cli::cli_alert_warning("Skipping plot generation because 'ggplot2' package is not installed")
    }
  }

  # Report processing time
  tout <- difftime(Sys.time(), t0)
  cli::cli_inform("Total processing time: {signif(as.numeric(tout), 3)} {attr(tout, 'units')}")

  return(result)

}

#-----

# From ?validate example
# library(fusionModel)
# library(dplyr)
# library(data.table)
# source("R/utils.R")
#
# fusion.vars <- c("electricity", "natural_gas", "aircon")
# predictor.vars <- names(recs)[2:12]
# fsn.path <- train(data = recs,
#                    y = fusion.vars,
#                    x = predictor.vars,
#                    weight = "weight")
# # Fuse back onto the donor data (multiple implicates)
# sim <- fuse(data = recs,
#              fsn = fsn.path,
#              M = 40)
#
# valid <- validate(observed = recs,
#                    implicates = sim,
#                    subset_vars = c("income", "education", "race", "urban_rural"),
#                    weight = "weight")

#------------------

#' @noRd
#' @export
plot_valid <- function(valid,
                       y = NULL,
                       path = NULL,
                       cores = 1,
                       ...) {

  # Check if ggplot is installed
  suppressMessages(ok <- require(ggplot2, quietly = TRUE, warn.conflicts = FALSE))
  if (!ok) stop("package 'ggplot2' must be installed for plot_valid() to work")

  if (inherits(valid, "validate")) {
    if (!is.data.frame(valid)) valid <- valid$data  # This forces 'valid' to just the data frame with validation results
  } else {
    stop("'valid' must be an object generated by validate()")
  }

  # Check inputs
  stopifnot({
    all(y %in% valid$y)
    is.null(path) | is.character(path)
  })

  # Create 'directory', if necessary
  if (!is.null(path)) {
    path <- normalizePath(path, mustWork = FALSE)
    if (!dir.exists(path)) dir.create(path, recursive = TRUE)
  }

  #---

  # Restrict fusion (y) variables, if requested
  if (!is.null(y)) valid <- filter(valid, y %in% !!y)

  #---

  # Confidence interval overlap
  # See Compare.CI() here: https://github.com/cran/synthpop/blob/master/R/compare.syn.r
  # CIoverlap(10, 20, 5, 25)
  # CIoverlap <- function(lwr_obs, upr_obs, lwr_sim, upr_sim) {
  #   L <- pmax(lwr_obs, lwr_sim)
  #   U <- pmin(upr_obs, upr_sim)
  #   0.5 * (((U - L) / (upr_obs - lwr_obs)) + ((U - L) / (upr_sim - lwr_sim)))
  # }

  #---

  errorFun <- function(obs, sim) {
    # out <- suppressWarnings({
    #   exp(abs(log(sim / obs))) - 1  # Morley 2018 preferred error metric (zeta); will be NA if ratio is negative and Inf if 'obs' is zero; https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017SW001669
    # })
    out <- abs((sim - obs) / obs)  # Conventional absolute percent error (gives Inf when obs = 0)
    #out <- ifelse(!is.finite(out), ape, out)  # If Morley's zeta is non-finite, replace with APE
    out[!is.finite(out)] <- NA  # If non-finite, return NA
    out[obs == sim] <- 0  # If 'obs' and 'sim' are identical, return zero error
    return(out)
  }

  # Calculate the error metrics for plotting
  vest <- valid %>%
    mutate(
      cont = is.na(level),

      # Point estimate error
      est = errorFun(obs = est.obs, sim = est.sim),

      # Relative uncertainty ratio (sim / obs)
      moe = (moe.sim / est.sim) / (moe.obs / est.obs),
      moe = ifelse(moe.sim == moe.obs, 1, moe),
      moe = ifelse(is.infinite(moe), NA, moe),

      # Point estimate value-added
      vad = 1 - abs(est.sim - est.obs) / abs(est.mean - est.obs),
      vad = ifelse(est.mean == est.obs, 0, vad),
      vad = pmax(0, vad)

    ) %>%
    # group_by(id, share, y, cont) %>%
    # summarize_at(c("est", "moe", "vad"), .funs = mean) %>%  # Collapses categorical levels to mean of performance metrics
    # ungroup() %>%
    mutate_if(is.numeric, ~ ifelse(is.finite(.x), .x, NA))  # Sets any non-finite values to NA

  #---

  # Conditional median of the error metrics
  cli::cli_inform("Smoothing validation metrics")
  y <- unique(vest$y)
  qest <- parallel::mclapply(y, function(v) {

    d <- filter(vest, y == v)

    est <- smoothQuantile(x = d$share, y = d$est, qu = 0.5)
    #est <- smoothMean(x = d$share, y = d$est, verbose = FALSE)

    moe <- smoothQuantile(x = d$share, y = d$moe, qu = 0.5)
    #moe  <- smoothMean(x = d$share, y = d$moe, verbose = FALSE)

    vad <- smoothQuantile(x = d$share, y = d$vad, qu = 0.5)

    out <- rbindlist(list(est = est, moe = moe, vad = vad), idcol = "metric", fill = TRUE)
    out[, CAT := !d$cont[1]]
    out[, VAR := v]
    setnames(out, "x", "SHR")
    return(out)

  }, mc.cores = cores) %>%
    data.table::rbindlist()

  # Drop invalid rows -- cases where the returned smoothed value is infeasible
  # qest <- qest %>%
  #   filter(y >= 0 | (y <= 1 & metric == "vad"))

  # qest <- qest %>%
  #   mutate(y = ifelse(metric %in% c("est", "moe"), pmax(0, y), pmin(1, y)))

  # Ensure feasible smoothed values

  min.max <- vest %>%
    group_by(y) %>%
    summarize_at(c("est", "vad", "moe"), list(min = min, max = max), na.rm = TRUE) %>%
    rename(VAR = y)

  qest <- qest %>%
    left_join(min.max, by = "VAR") %>%
    mutate(y = ifelse(metric == "est", pmax(pmin(y, est_max), est_min), y),
           y = ifelse(metric == "moe", pmax(pmin(y, moe_max), moe_min), y),
           y = ifelse(metric == "vad", pmax(pmin(y, vad_max), vad_min), y)) %>%
    select(metric:VAR)

  #---

  # Summary performance metrics (print to console)

  sum.perf <- dcast(qest, ... ~ metric, value.var = "y") %>%
    group_by(VAR) %>%
    summarize_at(c("est", "vad", "moe"), mean) %>%
    rename(y = VAR)
  cli::cli_inform("Average smoothed performance metrics across subset range:")
  print(as.data.frame(sum.perf), digits = 3, print.gap = 2)

  #---

  # Restrict the smooth results to x-range available for all of the variables
  # This ensures that the plots have a same/consistent x-axis for each of the y variables

  xrng <- range(qest$SHR)
  # xrng <- qest %>%
  #   group_by(VAR) %>%
  #   summarize(min = min(SHR), max = max(SHR), .groups = "drop") %>%
  #   summarize(min = max(min), max = min(max)) %>%
  #   unlist()

  qest <- qest %>%
    filter(SHR >= xrng[1], SHR <= xrng[2])

  #---

  # Create plot objects
  cli::cli_inform("Creating ggplot2 graphics{ifelse(is.null(path), '', ' and saving .png files to disk')}")

  # X-axis definition
  b <- c(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1) # Nice break marks on square root scale
  b <- b[max(1, which(b <= xrng[1])[1], na.rm = TRUE) : which(b >= xrng[2])[1]]
  pct <- function(x) paste0(as.character(x * 100), "%")
  xaxis <- scale_x_continuous(name = "Subset size (percent of total population)",
                              limits = xrng, breaks = b, trans = "sqrt", labels = pct)

  # ggplot elements to add to all plots
  plot.all <- list(xaxis,
                   theme_bw(),
                   theme(plot.title = element_text(face = "bold")),
                   guides(color = guide_legend(title = "Fusion variable"),
                          linetype = guide_legend(title = "Categorical")))

  #---

  # ggplot elements to add to each specific plot
  p1.add <- list(scale_y_continuous(name = "Median absolute percent error", n.breaks = 8, limits = c(0, NA), expand = expansion(mult = c(0.01, 0.05)), labels = pct),
                 labs(subtitle = "Comparison of point estimates"))

  p2.add <- list(scale_y_continuous(name = "Median value-added", n.breaks = 8, limits = c(0, 1), expand = expansion(mult = c(0.01, 0.05))),
                 geom_hline(yintercept = 1, linetype = 2),
                 labs(subtitle = "Value-added relative to naive estimates"))

  p3.add <- list(scale_y_continuous(name = "Median ratio of simulated-to-observed uncertainty", n.breaks = 8, limits = c(0, NA), expand = expansion(mult = c(0.01, 0.05))),
                 geom_hline(yintercept = 1, linetype = 2),
                 labs(subtitle = "Comparison of relative uncertainty (MOE / estimate)"))


  # p3.add <- list(scale_y_continuous(name = "Median ratio of simulated-to-observed MOE", n.breaks = 8, limits = c(0, NA), expand = expansion(mult = c(0.01, 0.05))),
  #                geom_hline(yintercept = 1, linetype = 2),
  #                labs(subtitle = "Bias in 90% margin of error (MOE)"))

  #---

  # Multi-variable plots
  # NOTE: Set 'linetype = CAT' to indicate whether each 'y' is continuous or categorical
  p1 <- ggplot(filter(qest, metric == "est"), aes(x = SHR, y = y, color = VAR, linetype = NULL)) + p1.add + plot.all + geom_line()
  p2 <- ggplot(filter(qest, metric == "vad"), aes(x = SHR, y = y, color = VAR, linetype = NULL)) + p2.add + plot.all + geom_line()
  p3 <- ggplot(filter(qest, metric == "moe"), aes(x = SHR, y = y, color = VAR, linetype = NULL)) + p3.add + plot.all + geom_line()
  #p3 <- ggplot(filter(qest, metric == "bias"), aes(x = SHR, y = y, color = VAR, linetype = NULL)) + p3.add + plot.all + geom_line()

  out1 <- list(p1, p2, p3)
  names(out1) <- c("est", "vad", "moe")

  if (!is.null(path)) {
    for (i in names(out1)) {
      suppressMessages(ggsave(filename = paste0("allvars_", i, ".png"), plot = out1[[i]], path = path, ...))
    }
  }

  #---

  # Single variable scatterplots

  out2 <- lapply(y, function(v) {

    fct <- 10  # Controls extent of extreme value inclusion in scatterplots
    pdata <- filter(qest, VAR == v)
    ed <- filter(vest, y == v, share >= xrng[1], share <= xrng[2])

    r <- median(ed$est, na.rm = TRUE) + c(-1, 1) * fct * mad(ed$est, na.rm = TRUE)
    p1 <- ggplot(filter(pdata, metric == "est"), aes(x = SHR, y = y)) +
      geom_point(data = filter(ed, est >= r[1], est <= r[2]),
                 aes(x = share, y = est), shape = 1) +
      #geom_point(data = filter(ed, error_est < max(pdata$est + ofct * pdata$peSE)), aes(x = share, y = error_pe), shape = 1) +
      # geom_ribbon(aes(ymin = pmax(pe - peSE * qt(0.975, DFpe), 0),
      #                 ymax = pmin(pe + peSE * qt(0.975, DFpe), ifelse(categorical, 1, Inf))),
      #             fill = "gray", alpha = 0.25, color = "red", linetype = "dotted") +
      p1.add + plot.all + labs(title = v) + geom_line(color = "red")

    r <- c(0, 1)
    p2 <- ggplot(filter(pdata, metric == "vad"), aes(x = SHR, y = y)) +
      geom_point(data = filter(ed, vad >= r[1], vad <= r[2]),
                 aes(x = share, y = vad), shape = 1) +
      p2.add + plot.all + labs(title = v) + geom_line(color = "red")

    r <- median(ed$moe, na.rm = TRUE) + c(-1, 1) * fct * mad(ed$moe, na.rm = TRUE)
    p3 <- ggplot(filter(pdata, metric == "moe"), aes(x = SHR, y = y)) +
      geom_point(data = filter(ed, moe >= r[1], moe <= r[2]),
                 aes(x = share, y = moe), shape = 1) +
      p3.add + plot.all + labs(title = v) + geom_line(color = "red")

    # r <- median(ed$bias) + c(-1, 1) * fct * mad(ed$bias)
    # p3 <- ggplot(filter(pdata, metric == "bias"), aes(x = SHR, y = y)) +
    #    geom_point(data = filter(ed, bias >= r[1], bias <= r[2]),
    #               aes(x = share, y = bias), shape = 1) +
    #    p3.add + plot.all + labs(title = v) + geom_line(color = "red")

    out <- list(p1, p2, p3)
    names(out) <- c("est", "vad", "moe")

    # Save plots to disk
    if (!is.null(path)) {
      for (i in names(out)) {
        suppressMessages(ggsave(filename = paste0(v, "_", i, ".png"), plot = out[[i]], path = path, ...))
      }
    }

    return(out)

  }) %>%
    setNames(y)

  #-----

  # Report location of output plots, if requested
  if (!is.null(path)) cli::cli_inform("Plots saved to: {path}")

  # Assemble final result
  result <- list(plots = c(out1, out2),
                 perf = sum.perf,
                 smooth = qest,
                 data = valid)
  if (!inherits(valid, "validate")) class(result) <- c("validate", class(result))
  return(result)

}
